
#- hosts: localhost
#  vars:
#    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
#    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
#    OPENTLC_ID: "{{ lookup('env','OPENTLC_ID') }}"
#  tasks:
#  - name: Create workstation inventory
#    add_host:
#       name: "workstation-{{OSP_GUID}}.{{OSP_DOMAIN}}"
#       group: workstation

- hosts: workstation
  become: yes
  roles:
    - osp-servers
