---

- name: Install app server packages
  package:
    name: "{{ payload }}"
    state: present

- name: Create Document Root Directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory
    owner: root
    group: tomcat
    mode: 0755

- name: Configure index.html
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
  notify: start_"{{ payload }}"

- name: Enable tomcat
  service:
    name: "{{ payload }}"
    state: started
    enabled: true
